title:            Ideas
description:      Some thoughts and ramblings.
url:              blog.rushir.co
paginate:         10

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# Theme specific settings
theme:            a
signoff:          Rushir
facebook_appid:   
google_analytics: 
disqus_shortname: 

owner:
  name:           Rushir
  avatar:         'https://secure.gravatar.com/avatar/afd3cc3e385d754183336c859d9e694a?s=420&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png'
  bio:            'I design, code, and write.'

links: 
  - name:         Home
    url:          rushir.co
  - name:         Categories
    url:          /categories
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://muan.co
  - name:         Email
    url:          mailto:rushikh@gmail.com
  - name:         GitHub
    url:          http://github.com/rushir