source: .
destination: ./public
exclude: ['CNAME', 'Rakefile', 'README.md', 'public', 'config.ru']

relative_permalinks: false

permalink: pretty

safe: true
url: http://blog.rushir.co

name: Rushir
description: 'Thoughts on programming, Unix and technology'

markdown: redcarpet
